clean_rpm_build_nodes:
  every:
    - '1m'
  class: 'CleanRpmBuildNodeJob'
  queue: middle
  description: 'Cleans RPM build nodes'

build_lists_publish_task_manager:
  every:
    - '3m'
  class: 'PublishTaskManagerJob'
  queue: middle
  description: 'Creates tasks for publishing'

build_lists_queues_monitoring:
  every:
    - '1m'
  class: 'BuildLists::QueuesMonitoringJob'
  queue: middle
  description: 'Monitoring for "user/mass-build" queues'

clean_api_defender_statistics:
  every:
    - '1d'
  class: 'CleanApiDefenderStatisticsJob'
  queue: low
  description: 'Cleans ApiDefender statistics'

clean_build_list_buildroot:
  every:
    - '1h'
  class: 'BuildLists::CleanBuildrootJob'
  queue: middle
  description: 'Cleans RPM buildroot from BuildList'

run_extra_mass_builds:
  every:
    - '5m'
  class: 'RunExtraMassBuildsJob'
  queue: low
  description: 'Run mass builds with relations'