clean_rpm_build_nodes:
  every:
    - '1m'
  class: 'CleanRpmBuildNodeJob'
  queue: middle
  description: 'Cleans RPM build nodes'

build_lists_publish_task_manager:
  every:
    - '3m'
  class: 'PublishTaskManagerJob'
  queue: middle
  description: 'Creates tasks for publishing'

clean_api_defender_statistics:
  every:
    - '1d'
  class: 'CleanApiDefenderStatisticsJob'
  queue: low
  description: 'Cleans ApiDefender statistics'

clean_build_list_buildroot:
  every:
    - '1h'
  class: 'BuildLists::CleanBuildrootJob'
  queue: middle
  description: 'Cleans RPM buildroot from BuildList'

run_extra_mass_builds:
  every:
    - '5m'
  class: 'RunExtraMassBuildsJob'
  queue: low
  description: 'Run mass builds with relations'

clear_builder_on_stale_buildlists:
  every:
    - '2m'
  class: 'BuildLists::ClearBuilderOnStaleBuildListsJob'
  queue: low
  description: 'Clear builder on build lists which are still pending'

remove_outdated_items:
  cron: '0 3 * * *'
  class: 'RemoveOutdatedItemsJob'
  queue: low
  description: 'Removes outdated mass builds, product buid lists and build lists'